---
title: "Control 1"
author:
- Fernando Rodriguez Guevara
- Rafael Arredondo
date: "16/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1
Calcule $n!$, la correspondiente aproximación de Stirling, la difernecia entre estas y la diferencia relativa para $n = 1, 2, ..., 12$.


```{r pressure, echo=TRUE}
n <- 1 : 12
f <- factorial(n)
stirling <- function(x) (2 * pi * n)^0.5 * (n / exp(1)) ^n
s <- stirling(n)
d <- f -s
dr <- d / f
data.frame(n, f, s, d, dr)
```

## 2

```{r pressure, echo=TRUE}
set.seed(20220118)
N <- 20000
x <- rgamma(N,shape=2,scale=1)
b <- seq(from=0, to=14, by=0.5)
out <- hist(x, breaks = b, xlab="observaciones", ylab="frecuencia", main="Distribución Gamma")
p_n <- out$density[5]-out$density[6]
p <- pgamma(2.5,2,1) - pgamma(2,2,1)
epsilon = p_n - p
```

## 3

## Binom

```{r pressure, echo=TRUE}
set.seed(20220118)
simulaciones <- 20000
param <- c(.5, .7, .9)

t_muestra <- 30
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 100
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 500
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)
```
## Pois

```{r pressure, echo=TRUE}
set.seed(20220118)
simulaciones <- 20000
param <- c(1, 4, 8)

t_muestra <- 30
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 100
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 500
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)
```
## Norm

```{r pressure, echo=TRUE}
set.seed(20220118)
simulaciones <- 20000

t_muestra <- 30
m_binom <- rbinom(simulaciones,25,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_binom, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 100
m_binom <- rbinom(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_binom, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 500
m_binom <- rbinom(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_binom, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)
```

## Gamma

```{r pressure, echo=TRUE}
set.seed(20220118)
simulaciones <- 20000
alfa <- c(1, 3, 5)
beta <- c(3, 1, 5)

t_muestra <- 30
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 100
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 500
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)
```
## Beta

```{r pressure, echo=TRUE}
set.seed(20220118)
simulaciones <- 20000
theta1 <- c(1, 1/2, 3, 1/2)
theta2 <- c(1, 2, 1/3, 1/2)

t_muestra <- 30
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 100
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)

t_muestra <- 500
m_gamma <- rgamma(simulaciones,shape=1,scale=3)
muestra <- c()
for ( i in 1 : simulaciones ) {
  muestra[i] = mean(sample(m_gamma, t_muestra, replace = TRUE))
}
z <- (muestra - 3) / sqrt(9/t_muestra)
hist(z)
```
